Features/22263 - Implementação das Mensagens
Unirota/Unirota.API pull request #24
Opened 2024-10-14 23:06 UTC by MiessiGomes

Fluxo de Mensagens criados e funcionando.

2024-10-14 23:14 UTC, NatanColleoni commented on src/Unirota.Application/Handlers/CriarMensagemRequestHandler.cs
> +            var usuarioId = _serviceContext.UsuarioId; // Supondo que o ID do usuário esteja disponível no contexto de serviço
Remover comentário

2024-10-14 23:16 UTC, NatanColleoni commented on src/Unirota.Application/Handlers/CriarMensagemRequestHandler.cs
> +            var usuarioId = _serviceContext.UsuarioId; // Supondo que o ID do usuário esteja disponível no contexto de serviço
Remover esse Handler

2024-10-14 23:22 UTC, NatanColleoni requested changes

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Queries/Mensagem/ConsultarMensagemPorIdQuery.cs
> +public class ConsultarMensagemPorIdQuery : IRequest<Mensagem>
Apagar esse arquivo

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Services/Mensagens/IMensagemService.cs
> +// using Unirota.Application.Commands.Mensagens;
Remover Comentario

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Services/Mensagens/IMensagemService.cs
> +    Task<bool> VerificarUsuarioPertenceAoGrupo(int usuarioId, int grupoId);
Remover metodo dessa service, e implementar na service de grupo

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Services/Mensagens/MensagemService.cs
> +    private readonly IRepository<Grupo> _grupoRepository;
Remover esse repository dessa Service

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Services/Mensagens/MensagemService.cs
> +            _serviceContext.AddError("Mensagem não encontrada");
necessario dar um return aqui, se não não para a execução do método

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Application/Specifications/Mensagens/ConsultarMensagemPorIdSpec.cs
> +public class ConsultarMensagemPorIdSpec : Specification<Mensagem>
Remover essa Spec

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Domain/Entities/Mensagens/Mensagem.cs
> +    // Método de fábrica estático
Remover comentario

2024-10-14 23:22 UTC, NatanColleoni commented on src/Unirota.Domain/Entities/Mensagens/Mensagem.cs
> +            throw new ArgumentException("O conteúdo da mensagem não pode ser vazio.");
Não usar throw exception

2024-10-14 23:32 UTC, MiessiGomes commented on src/Unirota.Application/Handlers/CriarMensagemRequestHandler.cs
> +            var usuarioId = _serviceContext.UsuarioId; // Supondo que o ID do usuário esteja disponível no contexto de serviço
Feito

2024-10-14 23:33 UTC, MiessiGomes commented on src/Unirota.Application/Queries/Mensagem/ConsultarMensagemPorIdQuery.cs
> +public class ConsultarMensagemPorIdQuery : IRequest<Mensagem>
Feito

2024-10-14 23:33 UTC, MiessiGomes commented on src/Unirota.Application/Services/Mensagens/IMensagemService.cs
> +// using Unirota.Application.Commands.Mensagens;
Feito

2024-10-14 23:40 UTC, MiessiGomes commented on src/Unirota.Application/Services/Mensagens/IMensagemService.cs
> +    Task<bool> VerificarUsuarioPertenceAoGrupo(int usuarioId, int grupoId);
Feito

2024-10-14 23:49 UTC, MiessiGomes commented on src/Unirota.Application/Services/Mensagens/MensagemService.cs
> +    private readonly IRepository<Grupo> _grupoRepository;
Feito

2024-10-14 23:49 UTC, MiessiGomes commented on src/Unirota.Application/Services/Mensagens/MensagemService.cs
> +            _serviceContext.AddError("Mensagem não encontrada");
Feito

2024-10-14 23:50 UTC, MiessiGomes commented on src/Unirota.Application/Specifications/Mensagens/ConsultarMensagemPorIdSpec.cs
> +public class ConsultarMensagemPorIdSpec : Specification<Mensagem>
Feito

2024-10-15 00:00 UTC, MiessiGomes commented on src/Unirota.Domain/Entities/Mensagens/Mensagem.cs
> +    // Método de fábrica estático
Feito

2024-10-15 00:00 UTC, MiessiGomes commented on src/Unirota.Domain/Entities/Mensagens/Mensagem.cs
> +            throw new ArgumentException("O conteúdo da mensagem não pode ser vazio.");
Feito

2024-10-15 00:02 UTC, NatanColleoni approved these changes

2024-10-15 00:02 UTC, merged